---
output:
  html_document: default
  pdf_document: default
  word_document: default
---
# Springboard Capstone Project 


## Problem - Predicting the Accuracy of Credit Card Default
At the end of March 2016, outstanding credit card debt totaled just over \$750 billion in the US alone. For households that carry an unpaid balance each month, the average debt was just over \$16,000 at the end of the same period. [Credit Card Data](https://www.valuepenguin.com/average-credit-card-debt) 

While outstanding credit card debt presents a risk to the consumer in the form of higher interest payments, it also presents a risk to the lender in the form of a potential default. Is it possible to identify characteristics of borrowers who are either more or less likely to default on their credit card debt?

  
## Client


Credit cards are usually issued by a bank or credit card company.  When the issuer is unlikely to collect credit card debt, they will write it off as a loss or charge-off.  At the end of 2016, credit card charge-offs were 3.37% for the top 100 US banks ranked by assets. [Write off Data](https://fred.stlouisfed.org/series/CORCCT100S) 

Assessing who is more likely to repay is at the heart of the lending industry. A predictive model that can more accurately profile a reliable borrower is very valuable information to financial institutions and can ultimatley help them reduce their write-off rates. Can we provide a predictive model 
of borrowers that might help credit card issuers reduce their charge-off rate?


## Data


While not focused on the US market, the data set for this project looked at one response variable (default or payment of credit card debt) for 30,000 Taiwanese credit card holders in October 2005. 

Y: Client action; 0 = no default; 1 = default

The following 23 independent variables were also included.

X1: Dollar amount of loan<br/>
X2: Gender of borrower (1 = male; 2 = female)<br/>
X3: Level of education (1 = graduate school; 2 = university; 3 = high school; 0, 4, 5, 6 = others)<br/>
X4: Marital status (1 = married; 2 = single; 3 = divorce; 0 = others)<br/>
X5: Age in years<br/>
X6-X11: Past monthly payments, X6 = repayment status in September of 2005;...; X11 = repayment status in April of 2005<br/>
The payment scale: -2 = No consumption; -1 = Paid in full; 0: The use of revolving credit; 1 = payment delay for 1 month; 
2 = payment delay for 2 months;...; 8 = payment delay for 8 months; 9 = payment delay for 9 months and above<br/>
X12-X17: Past monthly balances, X12 = balance in September of 2005;...; X17 = balance in April of 2005<br/>
X18-X23: Amount of previous payments, X18 = amount paid in September of 2005;...; X23 = amount paid in April of 2005<br/>

Data is available at the following link: [Data set](http://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients)

The data are provided in a CSV file.  The data will require some basic clean up.  Column names will need to be changed from X1, X2 etc. to more meaningful titles such as Gender, Education etc.  Columns X2-X4, X6-X11, and Y currently use integers to represent categorical data.  These values will need to be converted to names (male, female, bachelors degree, 2 month payment delay etc).


## Approach

With the dependent variable being default of payment, the question to answer is what independent variables are accurate predictors of a default? An important point to note is that a number of the independent variables are qualitative (marriage status, education level etc), while others are numerical values (monthly balances, loan amount etc).  

The first step will be to perform exploratory data analysis (EDA) and examine relationships between any of the independent variables and default.  For example, education level and default, or balance from month to month and default. 

In step two, independent variables that appear more frequently for default will require further exploration and more targeted questions. For example, is a combination of education level and a growing balance for 3 months significant? 

Finally, the results of the data analysis will need to be put into context. Does it make sense from an industry perspective that certain variables appear to have some predictive power?  What can we conclude about different profiles of borrowers?


## Deliverables


The deliverables for this project will all be loaded onto github. These will include the code used to manipulate and analyse data.  In addition, there will be a report including key findings, graphs, and final conclusions.
